//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vector_ChAsset : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<ChAsset>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vector_ChAsset(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vector_ChAsset obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vector_ChAsset() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          corePINVOKE.delete_vector_ChAsset(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public vector_ChAsset(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (ChAsset element in c) {
      this.Add(element);
    }
  }

  public vector_ChAsset(global::System.Collections.Generic.IEnumerable<ChAsset> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (ChAsset element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public ChAsset this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(ChAsset[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(ChAsset[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, ChAsset[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public ChAsset[] ToArray() {
    ChAsset[] array = new ChAsset[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<ChAsset> global::System.Collections.Generic.IEnumerable<ChAsset>.GetEnumerator() {
    return new vector_ChAssetEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new vector_ChAssetEnumerator(this);
  }

  public vector_ChAssetEnumerator GetEnumerator() {
    return new vector_ChAssetEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class vector_ChAssetEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<ChAsset>
  {
    private vector_ChAsset collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public vector_ChAssetEnumerator(vector_ChAsset collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public ChAsset Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (ChAsset)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    corePINVOKE.vector_ChAsset_Clear(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(ChAsset x) {
    corePINVOKE.vector_ChAsset_Add(swigCPtr, ChAsset.getCPtr(x));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = corePINVOKE.vector_ChAsset_size(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = corePINVOKE.vector_ChAsset_capacity(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    corePINVOKE.vector_ChAsset_reserve(swigCPtr, n);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public vector_ChAsset() : this(corePINVOKE.new_vector_ChAsset__SWIG_0(), true) {
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public vector_ChAsset(vector_ChAsset other) : this(corePINVOKE.new_vector_ChAsset__SWIG_1(vector_ChAsset.getCPtr(other)), true) {
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public vector_ChAsset(int capacity) : this(corePINVOKE.new_vector_ChAsset__SWIG_2(capacity), true) {
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  private ChAsset getitemcopy(int index) {
    global::System.IntPtr cPtr = corePINVOKE.vector_ChAsset_getitemcopy(swigCPtr, index);
    ChAsset ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChAsset(cPtr, true);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private ChAsset getitem(int index) {
    global::System.IntPtr cPtr = corePINVOKE.vector_ChAsset_getitem(swigCPtr, index);
    ChAsset ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChAsset(cPtr, true);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, ChAsset val) {
    corePINVOKE.vector_ChAsset_setitem(swigCPtr, index, ChAsset.getCPtr(val));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(vector_ChAsset values) {
    corePINVOKE.vector_ChAsset_AddRange(swigCPtr, vector_ChAsset.getCPtr(values));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public vector_ChAsset GetRange(int index, int count) {
    global::System.IntPtr cPtr = corePINVOKE.vector_ChAsset_GetRange(swigCPtr, index, count);
    vector_ChAsset ret = (cPtr == global::System.IntPtr.Zero) ? null : new vector_ChAsset(cPtr, true);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, ChAsset x) {
    corePINVOKE.vector_ChAsset_Insert(swigCPtr, index, ChAsset.getCPtr(x));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, vector_ChAsset values) {
    corePINVOKE.vector_ChAsset_InsertRange(swigCPtr, index, vector_ChAsset.getCPtr(values));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    corePINVOKE.vector_ChAsset_RemoveAt(swigCPtr, index);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    corePINVOKE.vector_ChAsset_RemoveRange(swigCPtr, index, count);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public static vector_ChAsset Repeat(ChAsset value, int count) {
    global::System.IntPtr cPtr = corePINVOKE.vector_ChAsset_Repeat(ChAsset.getCPtr(value), count);
    vector_ChAsset ret = (cPtr == global::System.IntPtr.Zero) ? null : new vector_ChAsset(cPtr, true);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    corePINVOKE.vector_ChAsset_Reverse__SWIG_0(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    corePINVOKE.vector_ChAsset_Reverse__SWIG_1(swigCPtr, index, count);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, vector_ChAsset values) {
    corePINVOKE.vector_ChAsset_SetRange(swigCPtr, index, vector_ChAsset.getCPtr(values));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

}
